const HomeTypes = {

    SET__HOME_COMPONENT_INFO: 'SET__HOME_COMPONENT_INFO',

    GET__HOME_COMPONENT_INFO: 'GET__HOME_COMPONENT_INFO',
    GET__HOME_COMPONENT_INFO__STATUS: 'GET__HOME_COMPONENT_INFO__STATUS',
    GET__HOME_COMPONENT_INFO__LOADING: 'GET__HOME_COMPONENT_INFO__LOADING',
    GET__HOME_COMPONENT_INFO__SUCCESS: 'GET__HOME_COMPONENT_INFO__SUCCESS',
    GET__HOME_COMPONENT_INFO__ERROR: 'GET__HOME_COMPONENT_INFO__ERROR',
}

export default HomeTypes;
